# @Date:   2017-03-20T16:36:18-04:00
# @Project: scatt-jacc-caj
# @Filename: travis.yml
# @Last modified time: 2017-03-20T16:53:05-04:00

#defining the language used
language: java

#setting jdk to java 8
jdk:
    - oraclejdk8

script:
- ./gradlew build

#the following lines help travis avoid uploading of unneccessary caches related to
#gradle functionality
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
