import static org.junit.Assert.assertEquals;
import org.junit.Test;
import java.util.Map;

/**
 * @author Clint Hall
 * @version 1
 */
public class ScriptSpecTest {
    /**
     * Test a good case.
     */
    @Test
    public void scriptSpecTest1() {
        scriptTestAbstraction("turnRight:", "Motion");
    }
    /**
     * Test a case with a non-existent opcode.
     */
    @Test
    public void scriptSpectTest2() {
        scriptTestAbstraction("foo", null);
    }
    /**
     * Used to test the commandsByType map generated by ScriptSpecs.
     * @param opcode The opcode to retrive from the map.
     * @param expectedCategory The expected category of opcode.
     */
    private void scriptTestAbstraction(String opcode, String expectedCategory) {
        Map<String, String> commandsByType = ScriptSpecs.getCommandsByType();
        String actualCategory = commandsByType.get(opcode);
//        System.out.println("expected : " + expectedCategory + ", actual: " + actualCategory);
        assertEquals(expectedCategory, actualCategory);
    }
}
